name: triprider
description: "관광데이터 공모전 TripRider FrontEnd"
publish_to: 'none'

version: 1.0.0+6

environment:
  sdk: ">=3.8.0-0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

  # Firebase
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1

  # 기본 기능
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  geolocator: ^12.0.0
  shared_preferences: ^2.2.0
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0

  # 지도/경로
  google_maps_flutter: ^2.9.0
  flutter_polyline_points: ^2.0.0
  kakao_map_plugin: ^0.3.7

  # 카카오
  kakao_flutter_sdk_user: ^1.9.7+3  # 카카오 로그인 API

  # 기타
  url_launcher: ^6.3.0
  webview_flutter: ^4.7.0
  cupertino_icons: ^1.0.8
  weather_icons: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/대표아이콘.png"

flutter:
  uses-material-design: true

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700

  assets:
    - assets/image/
    - assets/image/Gps.png
